### ISSUE TITLE
It must use the bearer authorization method

### ISSUE THREAD

**Issue by felipe-fontes** [meilisearch/strapi-plugin-meilisearch#340]
Guys, I'm trying to integrate my strapi with meilisearch in azure. I deployed using the `getmeili/meilisearch:latest`. I can use normally in postman or flutterweb. but the plugin doesn't work, I keep getting the same error 
```{"message":"The Authorization header is missing. It must use the bearer authorization method.","code":"missing_authorization_header","type":"auth","link":"https://docs.meilisearch.com/errors#missing_authorization_header"}```

Can you guys help me?

**Comment by brunoocasali** [comment]
Hello @felipe-fontes how are you?

Could you please send me the package version that you are using? 
Because we released a few days ago the new version of MeiliSearch server https://github.com/meilisearch/MeiliSearch/releases/tag/v0.25.0 and we released a new version of [strapi-plugin-meilisearch](https://github.com/meilisearch/strapi-plugin-meilisearch/releases/tag/v0.5.0) that supports the v0.25.0 of MeiliSearch server.

By the way, `getmeili/meilisearch:latest` doesn’t help me that much, because the latest tag is always being upgraded to the latest release, so in that way, I would need to know when you pulled out from docker hub!

[To check the current version you could use our guide](https://docs.meilisearch.com/reference/api/version.html#get-version-of-meilisearch) or make a cURL request :)

```curl
curl \
  -X GET 'http://localhost:7700/version'
```

Either way I would say to you to ensure you are on the latest version of the server and the strapi-plugin, it should be fine :)

**Comment by felipe-fontes** [comment]
Omg!!!, I lost 10h trying to fix it, thinking that was cors or something in azure. Thank you so much.
I had version 0.4.1 of strapi-plugin-meilisearch.

**Comment by brunoocasali** [comment]
OMG! 😆 

I'm glad I could help! Thanks for using MeiliSearch! 🎉 🌮
