### ISSUE TITLE
Set user agent name

### ISSUE THREAD

**Issue by vlowe85** [meilisearch/strapi-plugin-meilisearch#610]
**Description**
The search logs are populated with entries like `[2022-12-13T13:23:27Z INFO actix_web::middleware::logger] 172.19.16.209 "GET /indexes HTTP/1.1" 200 559 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.000419`

Can it be specific that this was the plugin?

**Basic example**
`[2022-12-13T13:23:27Z INFO actix_web::middleware::logger] 172.19.16.209 "GET /indexes HTTP/1.1" 200 559 "-" "strapi-plugin-meilisearch" 0.000419`

**Comment by bidoubiwa** [comment]
Hey @vlowe85, the plugin is using the [javascript client](https://github.com/meilisearch/meilisearch-js/). Since the client is also used on `browser`, we cannot alter the `USER-AGENT` header as altering it throws errors in chromium based browsers.

To tackle that, we created a custom header `X-Meilisearch-Client` in which you receive the required information:

https://github.com/meilisearch/strapi-plugin-meilisearch/blob/14f0764225a67596a25a5c87d0d33f7135ff5d5c/server/services/meilisearch/client.js#L15

In [meilisearch-js](https://github.com/meilisearch/meilisearch-js/blob/a570f329a2b59e7b396755ce326e01de7f2ee329/src/http-requests.ts#L44)

**Comment by bidoubiwa** [comment]
Does this answer your question @vlowe85 ?

**Comment by bidoubiwa** [comment]
I think this issue is solved :)
