### ISSUE TITLE
Semantic search with LangChain

### ISSUE THREAD

**Issue by Maxservais** [meilisearch/strapi-plugin-meilisearch#803]
**Description**
It would be amazing if this plugin supported Meilisearch's Vector Store to allow to generate vector embeddings for documents (strapi collection types)

**Goal**
Allow performing similarity search

**Comment by brunoocasali** [comment]
Hi @Maxservais, thanks for your interest in our tooling!

I'm pretty sure you can do the vector search already. Just be sure to use the correct Meilisearch version + enable the experimental feature from the API.

Did you face any issues while doing that?

**Comment by Maxservais** [comment]
Hey,

Thanks! I'll report back when I get around to doing it :)

**Comment by brunoocasali** [comment]
Hi @Maxservais, I will close this issue since I didn't get any feedback on your side. If you still have some issues, I recommend you visit our [discord channel](https://discord.gg/meilisearch). You'll get a quick feedback from our community.

In case of a bug, I encourage you to reopen this issue or create a new one!

Thanks a lot for using Meilisearch ❤️
